/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as v3Core from "./v3-core";
export type { v3Core };
import type * as v3Periphery from "./v3-periphery";
export type { v3Periphery };
